### ISSUE TITLE
Animation not shown all the time

### ISSUE THREAD

**Issue by sanderschnydrig** [piumaz/angular-pull-to-refresh#12]
Great package, much less intrusive than ngx-pull-to-refresh. I have one issue with it though.

On Web using DevTools and activating the device toolbar to simulate swiping the animation seems to work most of the time, the refreshEvent is being triggered every single time.

However sometimes the animation is not being shown and using it in a webview on mobile devices (Capacitor hybrid App) it is not shown most of the time.

All the settings are left at default and the component is inserted at the top of the Angular App Component HTML. App Module is added too according to the Documentation.

I didn't get any Errors or any other output in the console logs either.

**Comment by piumaz** [comment]
Thanks @sanderschnydrig, 
I tested with Capacitor (I've never used it) and it seems to work.
Do you have more info about it?
Could you make a video of what you see?

**Comment by sanderschnydrig** [comment]
Thanks a lot for your quick response @piumaz and great work on the repository all around!

I did make a video on my Oneplus 3 and Oneplus 8 Pro and interesingly, it doesn't show the animation on the first pull to refresh but it does show the animation on subsequent tries, although a bit unreliable with timing and smoothness.

Oneplus 3: https://photos.app.goo.gl/CThHu2YExA4pBYQ89
Oneplus 8 Pro: https://photos.app.goo.gl/7xXKwi3qd6TBBs5W8

Did you try Capacitor v3? Version 3.0.0 just came out a few days ago so I'm still on version 2.4.7. I will try version 3.0.0 in the coming days and keep you updated.

**Comment by piumaz** [comment]
Let me know @sanderschnydrig ...
The animation and event are triggered when the scrollTop equals zero and it was before.
So if you come from a scroll, the first time it doesn't work, and it's wanted.
I copied the same operation that you find on an Android Chrome.

**Comment by sanderschnydrig** [comment]
@piumaz if you look closely at the video I sent from the Oneplus 3 ( https://photos.app.goo.gl/CThHu2YExA4pBYQ89 ), the first time I'm pulling it doesn't show the animation but all the subsequent times.
Maybe the plugin just needs some time to initialize, and I haven't heard any complaints from my users yet so I'm guessing after error is probably minor across our limited range of devices we use for testing. Once we deploy I will have a bigger sample size and should the problem reoccur I will get bac kto you. I guess you can close the issue for now. 

Thanks again!

**Comment by a33nazarenko** [comment]
Hello, when I pull from the top to refresh, events and subscribe working, sent me the console, but the animation and view of spinner not showing, in Capacitor v3, any help please?

**Comment by piumaz** [comment]
Close, try 3.0.0 version
