### ISSUE TITLE
Dismiss refresher manually

### ISSUE THREAD

**Issue by matejvorcak** [piumaz/angular-pull-to-refresh#13]
Hi, thanks for great library. I only have one issue, when i got requests which takes a long time to get some data so
I would like to dismiss refresher manualy, not just by the timeout. Simpliest way is to edit src/lib/pull-to-refresh.component.ts file, add another @Input property:
```ts
@Input() autoDismiss = true
```
and in method onTouchEnd() add condition to dismiss refresher: 
```ts
if ( this.autoDismiss ) {
   setTimeout(() => {

        this.reset();

      }, 1500);
}
```

Also I would like to get reference to component from refresh event by adding this 

```ts
this.refresh.emit(this)
``` 
so I would be able to do this: 

```html
<pull-to-refresh 
  (refresh)="doRefresh($event)"
></pull-to-refresh>
``` 
and in component: 

```ts
doRefresh(event: PullToRefreshComponent) {
   // dismiss refresher manually
   myService.fetchSomeData().then( data => {
      event.reset();
      // do my job with the data
   } )
}
```

**Comment by piumaz** [comment]
Hi @matejvorcak, 
the component has the _disabled_ @Input

Maybe you could do this:

```ts
<pull-to-refresh 
  (refresh)="doRefresh()"
  [disabled]="disabledRefresh"
></pull-to-refresh>
```

and in component:
```ts
doRefresh() {
   this.disabledRefresh = true;
   myService.fetchSomeData().then( data => {
      this.disabledRefresh = false;
      // do my job with the data
   } )
}
```

It might work?

**Comment by matejvorcak** [comment]
Hi @piumaz I just tryied the code you post, but it does not works. If there is disabled @input set to true touch events are ignored so @output refresh will not be fired.

**Comment by piumaz** [comment]
so... you would like to keep the animation active until you get the response, right?
ok, as soon as I can I add the function on the next version.

**Comment by matejvorcak** [comment]
right

**Comment by piumaz** [comment]
@matejvorcak you can find the fuature on the new library version.
`npm install @piumaz/pull-to-refresh@2.1.0`

I added the dismiss method on the service, I didn't like passing the component instance in the output! :-)

**Comment by matejvorcak** [comment]
thanks, great job also very fast
