### ISSUE TITLE
pull to Refresh sensitivity issue

### ISSUE THREAD

**Issue by arjunckm** [piumaz/angular-pull-to-refresh#19]
currently, refresh sensitivity is very high, can we reduce it?

we have tried to updating the code in node_modules "piumaz-pull-torefresh.js" line no. 82 "this.pullToRefresh = 90;" we changed the value to "120" and it works fine.

but the problem is if we run "npm i " the updates will be gone, so this is giving problem in production.

is there any hack where we can overwrite the "this.pullToRefresh = 120;" value in our application?

Thank you in Advance

**Comment by Abhishek012345** [comment]
Hi Arjun, Thank you for raising this Issue. I am also facing same issue for refresh sensitivity. Can we get any solution for this problem? Looking forward for any solutions.

Thanks & Regards
Abhishek RP

**Comment by piumaz** [comment]
i added the _sensitivity_ **@input** in version 2.2.0
