### ISSUE TITLE
Not working with Angular 10 apps

### ISSUE THREAD

**Issue by Sampath-Lokuge** [piumaz/angular-pull-to-refresh#6]
Hi,

This is not working with Angular 10 apps. I have tried many ways. None of them worked. I hope you'll upgrade this module to Angular 10+.

```
'pull-to-refresh' is not a known element:
1. If 'pull-to-refresh' is an Angular component, then verify that it is part of this module.
2. If 'pull-to-refresh' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message
```

**Comment by piumaz** [comment]
Did you add it to the module?

**Comment by Sampath-Lokuge** [comment]
Yes, I have done it according to your doc. The problem here is this module supports only up to Angular `"@angular/core": "^8.2.14"`. Angular 9 and above is very different than 8. So you must update it to Angular 11 now.
